# Generated by Django 6.0 on 2025-12-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_otp_user_otp_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
